### ISSUE TITLE
Specifying a default graph URI

### ISSUE THREAD

**Issue by tsyber1an** [ruby-rdf/sparql-client#2]
Hi, may be i'm not clearly understand Sparql Client, but i didn't find way how to define graph repository

For example, i follow to http://dbpedia.org/sparql and define Default Graph URI http://tema.livejournal.com/data/foaf.rdf and Query text Select select ?name WHERE { ?x foaf:knows ?name} (all this i do in web browser)

BUT!!! where i should define Default Graph URI in Sparql Client library?

Thanks

**Comment by white-gecko** [comment]
According to the [SPARQL 1.1 Protocol](https://www.w3.org/TR/2013/REC-sparql11-protocol-20130321/) the default graph can be specified using the query parameter `default-graph-uri` for queries and `using-graph-uri` for update requests.

In which file does this need to be implemented?

**Comment by gkellogg** [comment]
From the code in

https://github.com/ruby-rdf/sparql-client/blob/28370e092a4fcfc17badeed72c2ae78c1cb6a470/lib/sparql/client.rb#L726-L731

it seems that you could simply pass this in as part of the endpoint URL:

```ruby
client = SPARQL::Client.new('http://dbpedia.org/sp^Cql?default-graph-uri=http%3A%2F%2Ftema.livejournal.com%2Fdata%2Ffoaf.rdf')
```

Which would work as long as you're using GET.

It would be reasonable to add something like `default_graph_uri` (and `named_graph_uri`) as instantiation options to `SPARQL::Client#initialize`. Code is also needed in `make_post_request` as described in [Long SELECT query using direct POST](https://www.w3.org/TR/2013/REC-sparql11-protocol-20130321/#select-longpost-direct).

Also, please add some examples for using this into the method preamble, and of course, tests, probably along the lines of the following:

https://github.com/ruby-rdf/sparql-client/blob/204355edf946f7baeb1c36f9aac83c5a53d3724e/spec/client_spec.rb#L124-L130
