### ISSUE TITLE
Feature request: support for COUNT

### ISSUE THREAD

**Issue by moustaki** [ruby-rdf/sparql-client#27]
(I tried to raise the request in the ruby-rdf space, but it doesn't seem to have an 'Issues' tab for some reason)

COUNT queries are very useful for a wide range of reasons, e.g. pagination. Right now the only way to do such queries in sparql-client is to write a full SPARQL query. It would be good to be able to do something like:

> client = SPARQL::Client.new 'http://dbpedia.org/sparql/'
> client.count(:uri).where([:uri, RDF.type, RDF::OWL.Class])
>   --> 73

I am using the following monkey-patch to do that: https://gist.github.com/3053508 - there must be a cleaner way to do it though.

**Comment by gkellogg** [comment]
Not well documented, but try the following:

```rdf
client = SPARQL::Client.new 'http://dbpedia.org/sparql/'
query = client.select(count: {uri: :c}).where([:uri, RDF.type, RDF::OWL.Class])

query.each_solution do |solution|
  puts solution.inspect
end
```
