### ISSUE TITLE
Union support in query generator

### ISSUE THREAD

**Issue by msalvadores** [ruby-rdf/sparql-client#32]
I cannot find any option or function in `query.rb` to set a `union` of query patterns as in:

http://www.w3.org/TR/sparql11-query/#alternatives

Maybe there is a way to do this but I cannot find it.

It seems like something like people would like to have. I have implemented some simple union support in a fork. I could document it, add tests and do a pull request.

**Comment by gkellogg** [comment]
This is complicated by the fact that a single query instance is used for building the queries. There is something similar in `#where` (recently added), where a where argument (or from block) can be a query. This might work as follows:

```rdf
query1 = SPARQL::Client::Query.new.where
query.select(:title).where([:book, RDF::Vocab::DC.title, :title]).union([:book, RDF::Vocab::DC11.title, :title])
```

It gets more complicated if you want optional blocks and filters. This might work as follows:

```rdf
query1 = SPARQL::Client::Query.select.where([:book, RDF::Vocab::DC11.title, :title]).filter("langmatches(?title, 'en')")
query.select(:title).where([:book, RDF::Vocab::DC.title, :title]).union(query1)
```

Or, in the block form:

```rdf
query.select(:title).where([:book, RDF::Vocab::DC.title, :title]).union do |q|
  q.select.where([:book, RDF::Vocab::DC11.title, :title]).filter("langmatches(?title, 'en')")
end
```
