### ISSUE TITLE
VALUES statements

### ISSUE THREAD

**Issue by ashmoran** [ruby-rdf/sparql-client#37]
I just ran into a situation where I unfortunately had to abandon sparql-client for a query because I needed to restrict one of the variables using a `VALUES` list. Is there any chance of supporting this in a future version?

**Comment by mcritchlow** [comment]
@no-reply @gkellogg I'm willing to take a stab at this. I'm curious what you think of the proposed syntax in this [gist](https://gist.github.com/mcritchlow/8147aa8ad643f5f34f90) have a few ?'s in there.

**Comment by gkellogg** [comment]
Thanks @mcritchlow, I need to consider this a bit more, but it looks promising.

Have you posted a [public domain dedication](http://unlicense.org/#unlicensing-contributions) as called for in the README? If not, please do so. Also add yourself to the Contributors list.

**Comment by mcritchlow** [comment]
@gkellogg thanks, sounds good. I'll sort out the public domain dedication in the meantime.

**Comment by gkellogg** [comment]
Closed via f15dec52a4366d94a557282ccbdbb3df76644b79.
