### ISSUE TITLE
SPARQL Query => SPARQL::Client::Query API Interface

### ISSUE THREAD

**Issue by ckristo** [ruby-rdf/sparql-client#60]
Hi,

I want to demonstrate the functionality of `sparql-client`s querying API; therefore I want to translate the following query string into API calls:

``` ruby
%q(
    PREFIX dbpedia-owl: <http://dbpedia.org/ontology/>
    PREFIX dbpprop: <http://dbpedia.org/property/>
    SELECT ?country ?population
    WHERE {
        ?country a dbpedia-owl:Country .
        ?country dbpprop:populationCensus ?population .
        FILTER ( isNumeric(?population) && ?population > 50000000 )
    }
    ORDER BY DESC(?population)
    LIMIT 5
)
```

=>

``` ruby
# - define ad-hoc vocabs
DBP_ONT  = RDF::Vocabulary.new('http://dbpedia.org/ontology/')
DBP_PROP = RDF::Vocabulary.new('http://dbpedia.org/property/')

client = SPARQL::Client.new('http://dbpedia.org/sparql')

# - define SPARQL query
query = client.select(:country, :population)
  .where([ :country, RDF.type, DBP_ONT.Country ])
  .where([ :country, DBP_PROP.populationCensus, :population ])
  # ...
```

but I just don't know how to "translate" the `FILTER` and the `ORDER BY` `DESC` parts. Anyone done that and can support me here?

**Comment by no-reply** [comment]
I can get you pretty close:

```ruby
client.select(:country, :population)
  .where([ :country, RDF.type, DBP_ONT.Country ])
  .where([ :country, DBP_PROP.populationCensus, :population ])
  .filter('isNumeric(?population) && ?population > 50000000 ')
  .order_by(:country)
```

To my knowledge, we have no DSL support for `DESC` or for constructing filters.

The filters seem like a fairly substantial work chunk, and maybe wouldn't present any usability over just expecting the user to input a filter string.

`DESC`/`ASC` might be more manageable, though.

ping: @gkellogg, @bendiken

**Comment by gkellogg** [comment]
DESCRIBE/ASC definitely easy to do. We also need some better uodate DSL.

**Comment by ckristo** [comment]
@gkellog How can I specify the `DESC` part of an `ORDER BY` clause with `SPARQL::Client::Query`'s `.order_by` method? I didn't get it, sorry..

**Comment by gkellogg** [comment]
That's a feature that needs to be added. I'll get around to looking at it soon.

**Comment by ckristo** [comment]
Created a PR that adds support for specifying the sort order direction with `.order()` :: #61
