### ISSUE TITLE
DSL support for `MINUS`

### ISSUE THREAD

**Issue by no-reply** [ruby-rdf/sparql-client#65]
SPARQL [`MINUS`](https://www.w3.org/TR/sparql11-query/#neg-minus) is missing from the DSL, and are hard to write into queries created using `SPARQL::Client::Query`.

We should consider ways to support this through the query builder.

**Comment by gkellogg** [comment]
There are probably several other constructs there are missing, for instance property-path support. It would be great to get more comprehensive support for SPARQL QUERY/UPDATE DSLs.

**Comment by gkellogg** [comment]
The solution described for #32 might work here too.
