### ISSUE TITLE
wrong parameter in HTTP headers?

### ISSUE THREAD

**Issue by dsatoh** [ruby-rdf/sparql-client#69]
I found a strange in HTTP headers made by sparql-client.
I dumped request header, and I could find 'Accept' header as below,

```
application/sparql-results+json, application/sparql-results+xml, text/boolean, text/tab-separated-values;p=0.8, text/csv;p=0.2, */*;p=0.1
```

I assume the quality parameter is `q=?.?`, not `p=?.?`.
This page may help,
[http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html](http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html)

Thanks.

**Comment by bendiken** [comment]
Thanks for the report, @dsatoh. This definitely looks like a typo, so I've remedied it just now in the master branch.
