### ISSUE TITLE
If you are using Wikidata, it requires User-Agent

### ISSUE THREAD

**Issue by ferdi2005** [ruby-rdf/sparql-client#94]
You can't query Wikidata without an User-Agent, so I propose to leave a note in the README to say that you should do things like:
` SPARQL::Client.new(endpoint, :method => :get, :headers => { 'User-Agent': 'MyBotName'})` to use Wikidata.

**Comment by gkellogg** [comment]
Actually, the library should provide a default for User-Agent. I'll add something suggesting that applications override this.
