### ISSUE TITLE
Feature request: support for SERVICE

### ISSUE THREAD

**Issue by s0rin** [ruby-rdf/sparql-client#99]
SERVICE is a feature of SPARQL 1.1 that allows an executing query to make a SPARQL protocol to another SPARQL endpoint.
It is very helpful to retrieve labels, as it reduces the complexity of SPARQL queries, but is not implemented in _sparql-client_ yet.

**Comment by gkellogg** [comment]
@s0rin, I added support for SERVICE on the develop branch (see inline documentation). As with other support, some patterns will be too complicated to express using SPARQL::Query.
